### ISSUE TITLE
Dropwizard Timer conversion method throws away useful metrics

### ISSUE THREAD

**Issue by btpeterson** [prometheus/client_java#525] opened 2020-02-11 19:49 UTC
The `fromTimer` method in DropwizardExports https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L110 converts a Metrics Timer into a Prometheus Summary without recording the min, max, mean, and standard deviation of the duration of some type of event, or the overall and moving averages of the rate of some type of event.

e.g. with Dropwizard 1.3.17 and Prometheus version 0.8.1

Where metrics for a Dropwizard Timer converted to a Prometheus Summary look like this:
`# HELP io_dropwizard_jetty_MutableServletContextHandler_requests Generated from Dropwizard metric import (metric=io.dropwizard.jetty.MutableServletContextHandler.requests, type=com.codahale.metrics.Timer)
 \# TYPE io_dropwizard_jetty_MutableServletContextHandler_requests summary
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.5",} 0.10800000000000001
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.75",} 0.21100000000000002
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.95",} 0.741
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.98",} 0.741
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.99",} 0.741
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.999",} 0.741
io_dropwizard_jetty_MutableServletContextHandler_requests_count 9.0`

It should look something of this form:
`# HELP io_dropwizard_jetty_MutableServletContextHandler_requests Generated from Dropwizard metric import (metric=io.dropwizard.jetty.MutableServletContextHandler.requests, type=com.codahale.metrics.Timer)
\# TYPE io_dropwizard_jetty_MutableServletContextHandler_requests summary
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.5",} 0.001
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.75",} 0.001
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.95",} 0.002
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.98",} 0.002
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.99",} 0.003
io_dropwizard_jetty_MutableServletContextHandler_requests{quantile="0.999",} 0.04
io_dropwizard_jetty_MutableServletContextHandler_requests_min 0.0
io_dropwizard_jetty_MutableServletContextHandler_requests_max 4.0E7
io_dropwizard_jetty_MutableServletContextHandler_requests_median 1000000.0
io_dropwizard_jetty_MutableServletContextHandler_requests_mean 1152216.7380545516
io_dropwizard_jetty_MutableServletContextHandler_requests_stddev 1843291.2698578946
io_dropwizard_jetty_MutableServletContextHandler_requests_count 1297.0
io_dropwizard_jetty_MutableServletContextHandler_requests{rate="m1",} 0.007373683673126385
io_dropwizard_jetty_MutableServletContextHandler_requests{rate="m5",} 0.8681037724467615
io_dropwizard_jetty_MutableServletContextHandler_requests{rate="m15",} 0.8406770125395507
io_dropwizard_jetty_MutableServletContextHandler_requests{rate="mean",} 0.568490738870207`

Where both of the metrics above are derived from Dropwizard's Timer metric:
`   "io.dropwizard.jetty.MutableServletContextHandler.requests" : {
      "count" : 1297,
      "max" : 0.04,
      "mean" : 0.0011522167380545517,
      "min" : 0.0,
      "p50" : 0.001,
      "p75" : 0.001,
      "p95" : 0.002,
      "p98" : 0.002,
      "p99" : 0.003,
      "p999" : 0.04,
      "stddev" : 0.0018432912698578947,
      "m15_rate" : 0.4613733266784683,
      "m1_rate" : 9.099848574976793E-7,
      "m5_rate" : 0.14349658844641472,
      "mean_rate" : 0.45971442765657716,
      "duration_units" : "seconds",
      "rate_units" : "calls/second"
    }`

**Comment by brian-brazil** [comment] 2020-02-11 20:03
Dupe of #390, #308, and #106

**Closed by brian-brazil** 2020-02-11 20:03 UTC

**Comment by btpeterson** [comment] 2020-02-11 20:32
@brian-brazil, The explanation there makes sense, although in this case, those additional "less useful statistics" aren't redundant. 

You can't really get average from the quantiles here since the distribution is arbitrary, so for metrics of this form (duration of something happening combined with rate of something happening), that average can't be computed unless we instrument our code to record the metric ourselves.

**Comment by btpeterson** [comment] 2020-02-11 21:11
I disagree with the assumption that any pre-calculated averages are not useful and add clutter. The request duration is a good example here because the quantiles don't provide enough information to calculate an average, so calculating an average would require either duplicating what Dropwizard Metrics is already doing or circumventing the Prometheus DropwizardExport to save that information.

**Comment by Gr33nbl00d** [comment] 2023-04-12 22:29
@btpeterson you are right this is very ignorant. But if you are still interested its easy to add these values again
