### ISSUE TITLE
Collector.register's signature doesn't make sense

### ISSUE THREAD

**Issue by mberndt123** [prometheus/client_java#431] opened 2018-10-23 13:00 UTC
Hi,

the current signature of Collector.register is
```java
public <T extends Collector> T register(CollectorRegistry registry)
```
This doesn't make sense, there is no correct implementation of such a signature. It is impossible to return something of type T for every subtype T of Collector, yet this is what the signature promises. Among others, this leads to dead code warnings when using this library with the Scala programming language.

I can see two possible solutions to this problem: simplify the method's return type to `Collector` or `void`, or make `T` a type parameter of the Collector class itself like so:
```java
public abstract class Collector<T extends Collector> {
  …
  protected abstract T self(); // override in subclasses to return `this`
  public T register(CollectorRegistry registry) {
    registry.register(this);
    return self();
  }
  …
}
```

**Comment by brian-brazil** [comment] 2018-10-23 13:35
What you propose would be a breaking change for all existing users. It promises to return a T which is a subclass of Collector, and does just that by returning itself. This way of doing things ensures that the resultant type is not Collector and thus the user doesn't have to cast it.

**Comment by mberndt123** [comment] 2018-10-23 18:53
Hi @brian-brazil, thanks for responding.

> What you propose would be a breaking change for all existing users.

I realize that it can not be changed in a bugfix release. 

> promises to return a T which is a subclass of Collector, and does just that by returning itself

No, that is not what is promises. It promises to return an _arbitrary_ subtype of Collector that the _caller gets to choose_.

> This way of doing things ensures that the resultant type is not Collector and thus the user doesn't have to cast it.

Uh, have you ever actually tried that? Because that is not how it works. Something like this won't compile:
```java
Counter.build().name("foo").help("bar").create().register().inc();
```
The compiler has no reason to infer `T = Counter`, hence it doesn't know that the returned value has an `inc` method. What you have to write instead is this:
```java
Counter.build().name("foo").help("bar").create().<Counter>register().inc()
```
I don't see how that's any better than a cast. In fact it's much worse, because when there is a context to infer the type parameter from, the Java compiler will do just that. So this compiles and crashes at run-time:
```java
Gauge g = Counter.build().name("foo").help("bar").create().register(); // no cast needed
```

If you want to offer a convenient, fluent interface, you need to do what I proposed above and declare the type parameter on the class rather than the method.

**Comment by brian-brazil** [comment] 2018-10-23 19:03
The current logic was added in #86 for the purposes of working with Scala.

> Counter.build().name("foo").help("bar").create().register().inc();

This is not sane usage, a counter should be assigned to a field.

**Comment by mberndt123** [comment] 2018-10-23 19:11
> This is not sane usage, a counter should be assigned to a field.

That is besides the point. Please take another look at my last example:
```java
Gauge g = Counter.build().name("foo").help("bar").create().register(); // no cast needed
```
This looks innocuous at first but will crash at run-time. Sorry, but this is not a safe API design

**Comment by brian-brazil** [comment] 2018-10-23 19:22
It'll crash immediately at startup with expected usage, not during serving. Do you have a suggestion that's not a breaking change?

**Comment by mberndt123** [comment] 2018-10-23 19:29
By the way, the current signature wasn't introduced in #86. That signature was `SimpleCollector.Builder.register`, not `Collector.register`. And in fact that commit does exactly what I propose to do with `Collector` too: add a type parameter to the class (in this case the `Builder` class) and remove it from the `create` and `register` methods.

**Comment by mberndt123** [comment] 2018-10-23 19:35
Note that most users would not be affected if a type parameter is added to `Collector`. It would only break compatibility for users who derive from the `Collector` class. I would guess that not many people do that, and it's a change that is trivial to adapt to. I can send a PR if you like…

**Comment by mberndt123** [comment] 2018-10-23 19:44
> It'll crash immediately at startup with expected usage

By the way, this is actually not true when you declare the variable using a type parameter (because of erasure). 

```java
class Foo<T extends Collector> {
  public T t = Counter.build().name("foo").help("bar").create().register();
}

new Foo<Gauge>();
```
This will compile and not crash, until somebody tries to use `t`.

**Comment by mberndt123** [comment] 2018-10-23 20:30
> This is not a sane usage.

I disagree with the notion that every usage you don't like is “not sane”. The only thing I see here that isn't sane is the signature of the method.

**Comment by eugengarkusha** [comment] 2018-10-23 21:05
> > Counter.build().name("foo").help("bar").create().register().inc();
> 
> This is not sane usage, a counter should be assigned to a field.

@brian-brazil pls correct me if I am wrong but one of the main purposes of type system is to prevent accidental bugs caused by unintentional "not sane usage". 

For example, passing a Boolean into a method that accepts strings is obviously not a sane usage of that method but compiler helps us out there emitting an error and not letting this break at runtime.


> It'll crash immediately at startup with expected usage, not during serving.....

When things pass compilation - they get into run time.  There is no such a notion of "just before the real run time".

@brian-brazil  do you agree that this signature can be improved in future releases to protect inexperienced programmers from accidental bugs?

**Comment by brian-brazil** [comment] 2018-10-23 21:17
> There is no such a notion of "just before the real run time".

There's initialisation, and then there's serving. This is one of a few errors that'd only get caught on initialisation.

> @brian-brazil do you agree that this signature can be improved in future releases to protect inexperienced programmers from accidental bugs?

I'm open to non-breaking suggestions.

**Comment by brian-brazil** [comment] 2018-10-24 09:50
I care about source compatibility. Is this actually something you've run into, or more a theoretical concern?

**Comment by mberndt123** [comment] 2018-10-24 10:49
It causes issues for me because it causes dead code warnings in the Scala compiler. The Scala compiler understands that there is no sound way to implement a signature like that.

**Comment by mberndt123** [comment] 2018-11-03 16:43
So I take it nothing is going to happen here?

**Comment by mr-git** [comment] 2019-06-27 08:37
instead of "nice looking" `val c = Counter.build().name("foo").help("bar").create().register()` we changed code to 
```
val c: Counter = {
  val c = Counter.build().name("foo").help("bar").create()
  CollectorRegistry.defaultRegistry.register(c)
  c
}
```

This ugly workaround does the trick and doesn't trigger "dead-code after `register()` call` warning.

**Comment by brian-brazil** [comment] 2019-08-08 10:05
Sounds like there's nothing we can do here, and there is a workaround.

**Closed by brian-brazil** 2019-08-08 10:05 UTC

**Comment by mberndt123** [comment] 2019-08-10 09:31
> Sounds like there's nothing we can do here, and there is a workaround.

Oh, you very much can do something, and you did in #86. The issue is you don't _want_ to, please be honest about that.

**Comment by mr-git** [comment] 2019-08-11 07:04
maybe we could add second set of API, with better types and users would be able to pick any of APIs to use?
