### ISSUE TITLE
 WARNING: sendResponseHeaders: being invoked with a content length for a HEAD request

### ISSUE THREAD

**Issue by yakirgb** [prometheus/client_java#685] opened 2021-08-16 12:48 UTC
Hi,
I'm using JAR: `jmx_prometheus_httpserver-0.16.1-jar-with-dependencies.jar` to monitor HDFS NameNodes 
Every 60 seconds i'm getting this warning:
```
Aug 16 12:34:59 nn00103 java[22008]: Aug 16, 2021 12:34:59 PM sun.net.httpserver.ExchangeImpl sendResponseHeaders
Aug 16 12:34:59 nn00103 java[22008]: WARNING: sendResponseHeaders: being invoked with a content length for a HEAD request
````
The exporter is working without any problem, only printing warning. 
Thank you,Yakir

**Comment by dhoard** [comment] 2021-09-01 17:28
Created PR ( https://github.com/prometheus/client_java/pull/688 ) to resolve the issue. @fstab please review.

**Comment by fstab** [comment] 2021-09-10 09:54
Sorry for the delay. Could you let me know which Java version you are using? I cannot reproduce this.

To me it looks like the warning is wrong, according to to [the HTTP/1.1 Spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13) there must be a `Content-length` header.
> The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, **in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET.**

**Comment by dhoard** [comment] 2021-09-10 17:15
I'm running Azul's OpenJDK version 11...

openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed \`mode)\`

\-

The warning is in the OpenJDK 11 though OpenJDK 13 codebase, so can't explain why you're not seeing it...

https://github.com/openjdk/jdk11u/blob/63fc945c1d4cdc893d89796804acfe0ce9341860/src/jdk.httpserver/share/classes/sun/net/httpserver/ExchangeImpl.java#L238

https://github.com/openjdk/jdk17/blob/a37254c79fa5973465d90f4b52ab88fe68016c9f/src/jdk.httpserver/share/classes/sun/net/httpserver/ExchangeImpl.java#L238

\-

The change was made based Java bug #6886723 and the proposed workaround to remove the warning...

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6886723

\-

I did some further debugging and determined the correct way to resolve this warning is to set the `Content-Length` explicitly and then use `-1` in the `sendResponseHeaders()` method call if it's a `HEAD` request. This keeps the correct `Content-Length` header vallue in the response and removes the warning.

```
long contentLength = response.size();
t.getResponseHeaders().set("Content-Length", String.valueOf(contentLength));
if (t.getRequestMethod().equals("HEAD")) {
    contentLength = -1;
 }
t.sendResponseHeaders(HttpURLConnection.HTTP_OK, contentLength);
response.writeTo(t.getResponseBody());
```

The change is trivial, but requires a refactor of the `TestHTTPServer`JUnit test class to capture both the content-length and response body for testing.

I will update the PR with these changes for you to review.

**Comment by fstab** [comment] 2021-09-11 22:07
Thanks for the explanation, and thanks for your fix. It's merged now. The warning will be gone with the next release of `client_java`.

**Closed by fstab** 2021-09-11 22:07 UTC
