### ISSUE TITLE
Extra comma for metrics with labels

### ISSUE THREAD

**Issue by fraisse** [prometheus/client_java#351] opened 2018-03-08 16:42 UTC
https://github.com/prometheus/client_java/blob/0deffbc4cf06513ca1c75b00936db3956ca1fb1c/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L43

It seems there will systematically be a comma at then of the labels, no?

**Comment by brian-brazil** [comment] 2018-03-08 17:06
Dupe of #210

**Closed by brian-brazil** 2018-03-08 17:06 UTC
