### ISSUE TITLE
PrometheusEndpoint 500 error with failed "application/vnd.google.protobuf" http header

### ISSUE THREAD

**Issue by linux-china** [prometheus/client_java#253] opened 2017-06-09 08:24 UTC
I have following code with prometheus endpoint, and management port is 8081.  

```
@Configuration
@EnableSpringBootMetricsCollector
@EnablePrometheusEndpoint
public class PrometheusConfiguration {

    @Bean
    public ServletRegistrationBean servletRegistrationBean() {
        DefaultExports.initialize();
        return new ServletRegistrationBean(new MetricsServlet(), "/prometheus");
    }

}
```
and my scrape configuration as following: 

```
  - job_name: 'tsdbdemo'

    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['192.168.99.1:8081']

```

and Prometheus always reports down state for the target. and I try with following command 

```
curl -H 'Accept: application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited' http://192.168.99.1:8081/prometheus
```
Prometheus endpoint reports 500 error, but it's ok for MetricsServlet.  Any idea to fix this problem?

**Comment by JMesens** [comment] 2017-06-30 13:49
Had a similar problem but fixed it by adding [this](https://github.com/predic8/client_java/blob/dae29303a9e3ee228d81409cba461a650dbd5d54/simpleclient_spring_boot/src/main/java/io/prometheus/client/spring/boot/PrometheusMvcEndpoint.java) file as a workaround. (from https://github.com/prometheus/client_java/issues/265)

**Comment by brian-brazil** [comment] 2017-07-10 12:56
Sounds like a dupe of #265

**Closed by brian-brazil** 2017-07-10 12:56 UTC
